### PR TITLE
Add multiple scattering to the standard labeler

### PR DESCRIPTION
**Pull request by Will-D2099**
I think these events should be classified as diffuse similar to the other events in which are included in the or statement.

### CODE REVIEW

**Comment by vhewes** [comment]
i think the quality that identifies this specific case as diffuse is the _start_ process, not the _end_ process. i'd tag this as diffuse based on the start process (i believe you said this particle's start process was photoelectric?) rather than the end process. once you make that switch, i think this is ready to be merged :)

**Comment by Will-D2099** [comment]
I see the reason I did it like this is because I found another process in the muon samples labelling failed for electron with start process "muPairProd" and end process "msc" but I can add both muPairProd and phot for the start process if they should both be classified as diffuse.

**Comment by vhewes** [comment]
yeah, please add both start processes instead of using the end process. i think those dictate the semantic label, and anything we add here needs to be generalisable. once that's done, i can merge this in. thank you!

**Review by vhewes — APPROVED** [review]
looks good! feel free to merge it in

**Pull request merged**
